# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/0f5704d0-277b-4a90-9f72-6b4d73c16d1b";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/7450-480E";
      fsType = "vfat";
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/0f5704d0-277b-4a90-9f72-6b4d73c16d1b";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/0f5704d0-277b-4a90-9f72-6b4d73c16d1b";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/home/.snapshots" =
    { device = "/dev/disk/by-uuid/0f5704d0-277b-4a90-9f72-6b4d73c16d1b";
      fsType = "btrfs";
      options = [ "subvol=@snap_home" ];
    };
  
fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/0f5704d0-277b-4a90-9f72-6b4d73c16d1b";
      fsType = "btrfs";
      options = [ "subvol=@log" ];
    };

  fileSystems."/var/lib/machines" =
    { device = "/dev/disk/by-uuid/0f5704d0-277b-4a90-9f72-6b4d73c16d1b";
      fsType = "btrfs";
      options = [ "subvol=@machines" ];
    };

  fileSystems."/var/lib/postgres" =
    { device = "/dev/disk/by-uuid/0f5704d0-277b-4a90-9f72-6b4d73c16d1b";
      fsType = "btrfs";
      options = [ "subvol=@postgres" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/ee02b3de-4698-4aa7-9100-f9dd22898dcd"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp5s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp6s0.useDHCP = lib.mkDefault true;

  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
